#!/bin/bash

object1='{"a":{"b":{"c":"d"}}}'
key1="a/b/c"

object2='{"x":{"y":{"z":"a"}}}'
key2="x/y/z"

value=$(echo "$object1" | jq -r ".$key1")
echo "$value"  

value=$(echo "$object2" | jq -r ".$key2")
echo "$value"  